---

- hosts: tower_instances,tag_lab_role_tower
  gather_facts: no
  vars:
    ansible_ssh_user: ec2-user
    ansible_python_interpreter: "python"
  vars_files:
    - aws_vars.yml
    - tower_vars.yml
  roles:
    - tower_config
