---

- hosts: localhost
  gather_facts: no
  vars_files:
    - aws_vars.yml
  vars:
    route53_placeholder_ip: "104.67.28.83"
  tasks:
    - name: Create Hostnames
      set_fact:
        domains: "{{ domains | default('') | list }}  + ['tower-{{ lab_user }}-{{ item }}.{{ domain_name }}', 'master-{{ lab_user }}-{{ item }}.{{ domain_name }}', '*.apps-{{ lab_user }}-{{ item }}.{{ domain_name }}']"
      with_sequence: start="{{ student_count_start }}" end="{{ student_count_end }}"
    - name: Register route53 entries
      route53:
        command: create
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"
        zone: "{{ domain_name }}"
        type: A
        overwrite: True
        ttl: 60
        record: "{{ item }}"
        value: "{{ route53_placeholder_ip }}"
        wait: yes
      with_items: "{{ domains }}"
    - name: Letsencrypt
      include_role:
        name: letsencrypt
      vars:
        letsencrypt_domains: "{{ domains }}"
