---
- name: Create OpenShift Hosts
  hosts: localhost
  gather_facts: no
  vars:
    osp_domain_name: osp.example.com
    osp_instances:
    - type: app
      name: node2
      meta:
        nodes: 'true'
        new_nodes: 'true'
        osev3: 'true'
        node_type: app
  tasks:
  - os_server:
      name: "{{ item.name }}.{{ osp_domain_name }}"
      cloud: devstack
      state: present
      image: rhel-guest-image-7.3
      volume_size: 10
      boot_from_volume: yes
      terminate_volume: yes
      flavor: ocp.node
      key_name: tower
      userdata: "{{ lookup('template', 'user_data.j2') }}"
      security_groups:
      - default
      - openshift
      nics:
      - port-name: "openshift-{{ item.name }}"
      meta: "{{ item.meta}}"
    with_items:
    - "{{ osp_instances }}"
    register: instance_create

  - name: Wait for ssh
    wait_for:
      port: 22
      host: "{{ item.server.accessIPv4 }}"
      timeout: 600
    with_items:
    - "{{ instance_create.results }}"
