---
- import_tasks: credentials/machine.yml
  when: tower_credential_machine_config|bool == true
  tags: creds
- import_tasks: credentials/cloud.yml
  when: tower_credential_cloud_config|bool == true
  tags: creds
...
